### ISSUE TITLE
Create a Web Page with Youtube videos embedded

### ISSUE THREAD

**Issue by learn-2earn** [learn-2earn/hacktober2020#1]
You have to create a webpage in which youtube videos are embedded. 
Minimum 3 videos should be there and the web page should be responsive with a Navbar at top and paragraphs at bottom.
Create a PR only when your work is ready. 
#hacktoberfest2020 #hacktoberfest #hacktoberfest

**Comment by Aayush-Bhatt** [comment]
I can work on this issue.

**Comment by learn-2earn** [comment]
> I can work on this issue.

ok go ahead.

**Comment by anacarolinaarellano** [comment]
May I work this issue too?

**Comment by Aayush-Bhatt** [comment]
> May I work this issue too?

ok go ahead
